//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUni
{
    using System;
    using System.Collections.Generic;
    
    public partial class conference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public conference()
        {
            this.conference_attenders = new HashSet<conference_attenders>();
        }
    
        public int id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> date_and_time { get; set; }
        public string duration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<conference_attenders> conference_attenders { get; set; }
    }
}
